### ISSUE TITLE
Add unit tests for API Endpoints.

### ISSUE THREAD

**Issue by RachealN** [wikimedia/MediaWiki-Action-API-Code-Samples#69]

**Comment by RachealN** [comment]
@srishi, I read through the wikimedia API Endpoint and I  realised the sample code has no tests written for the endpoints . and i would really take an a honor of writting the tests given a chance as my contribution. Thanks

**Comment by tuxology** [comment]
@RachealN Hey, thanks for chiming in. I had a small discussion with @srish regarding this as well. Since these are very basic examples, tests for APIs are not a priority. Also, since such tests are already existing for all APIs internally in MediaWiki API implementation and testing infrastructure, it makes sense to not duplicate the efforts here. There can be plenty of other tasks that can be done - for example, more complex code samples that use multiple APIs in tandem to solve interesting use-cases
