### ISSUE TITLE
Extending the "Nearby Places Viewer" with street address using GeoPi

### ISSUE THREAD

**Issue by mchesler613** [wikimedia/MediaWiki-Action-API-Code-Samples#77]
Hi @srish ,
I was wondering if I can extend the "Nearby Places Viewer" by adding a street address to the form and 
using GeoPi to produce the latitude and longitude?  Please let me know if this is something that you will accept a contribution from.  I have a deadline to meet to submit contributions with Outreachy as well as Udacity.  Thank you for your attention.

**Comment by tuxology** [comment]
@mchesler613 Hi, thanks for your input! Since the demo app adequately covers the API usage, it won't make much impact on adding a very similar feature IMO. @srish suggested me that we wait for more micro-tasks to show up here: https://phabricator.wikimedia.org/T215682 as she irons out some specifics of future directions for the API code samples repo.
